// This code was autogenerated with `dbus-codegen-rust -c blocking --file target/nm-1.10.14/NetworkManager-1.10.14/introspection/org.freedesktop.NetworkManager.DHCP6Config.xml`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait DHCP6Config {
    fn options(&self) -> Result<arg::PropMap, dbus::Error>;
}

#[derive(Debug)]
pub struct DHCP6ConfigPropertiesChanged {
    pub properties: arg::PropMap,
}

impl arg::AppendAll for DHCP6ConfigPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.properties, i);
    }
}

impl arg::ReadAll for DHCP6ConfigPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(DHCP6ConfigPropertiesChanged {
            properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for DHCP6ConfigPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.NetworkManager.DHCP6Config";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> DHCP6Config for blocking::Proxy<'a, C> {

    fn options(&self) -> Result<arg::PropMap, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.freedesktop.NetworkManager.DHCP6Config", "Options")
    }
}
