// This code was autogenerated with `dbus-codegen-rust -c blocking --file target/nm-1.10.14/NetworkManager-1.10.14/introspection/org.freedesktop.NetworkManager.WiMax.Nsp.xml`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait WiMaxNsp {
    fn name(&self) -> Result<String, dbus::Error>;
    fn signal_quality(&self) -> Result<u32, dbus::Error>;
    fn network_type(&self) -> Result<u32, dbus::Error>;
}

#[derive(Debug)]
pub struct WiMaxNspPropertiesChanged {
    pub properties: arg::PropMap,
}

impl arg::AppendAll for WiMaxNspPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.properties, i);
    }
}

impl arg::ReadAll for WiMaxNspPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(WiMaxNspPropertiesChanged {
            properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for WiMaxNspPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.NetworkManager.WiMax.Nsp";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> WiMaxNsp for blocking::Proxy<'a, C> {

    fn name(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.freedesktop.NetworkManager.WiMax.Nsp", "Name")
    }

    fn signal_quality(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.freedesktop.NetworkManager.WiMax.Nsp", "SignalQuality")
    }

    fn network_type(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.freedesktop.NetworkManager.WiMax.Nsp", "NetworkType")
    }
}
